"use client";

import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider, theme } from "antd";
import { Oxygen } from "next/font/google";

const oxygen = Oxygen({
  subsets: ["latin"],
  weight: "300",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const darkMode = true
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              algorithm: darkMode ? theme.darkAlgorithm : theme.compactAlgorithm,
              token: {
                // Seed Token
                colorPrimary: darkMode ? "#c49b7e" : "#493628",
                colorPrimaryBg: darkMode ? "#fcf6f34f" : "#f5e6dd9f",
                colorPrimaryBgHover: darkMode ? "#977c6825" : "#49362825",
                // Alias Token
                colorBgContainer: darkMode ? "#111111" : "#FFFFFF",
                colorBgBase: darkMode ? "#2f2f2f" : "#FFFFFF",
                // Radius
                borderRadius: 4,
                fontFamily: oxygen.style.fontFamily,
              },
            }}
          >
            {children}
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
